### ISSUE TITLE
using weka by docker

### ISSUE THREAD

**Issue by elahia** [jamesmstone/dockerfiles#3]
Hi, 
i'm using openface which is a package for detecting some features of human face, then i need to send this features to weka for classifying, i couldn't find any way to call weka in c++, so i decided to use docker, 
my goal is defining two containers, one contains openface which provide the input for weka and the other a container for weka,

so how can i use your docker file for this purpose???
thanks in advance

**Comment by jamesmstone** [comment]
Hi Elahia,
I have no knowledge of Openface, but after having a quick read of your gh issue: https://github.com/TadasBaltrusaitis/OpenFace/issues/409
I imagine  you could use `docker-compose` to help you .
Am I correct in that `openface` outputs csv files you would like to process ?
if so you could create a [`volume`](https://docs.docker.com/compose/compose-file/#volume-configuration-reference) that the containers share.
You might also find you have to build your own image based off my weka image. using a `dockerfile` and reference that in `docker-compose`.
Finally, depending on your use case you might find it bestto use weka over the [command line](https://stackoverflow.com/questions/15441428/learning-weka-on-the-comand-line#15448278)

**Comment by elahia** [comment]
Hi James,
Thank you for your reply, actually, now i stick in one step before using weka! So let me please pass this step then i will go for the details you provide me, 

Thank you so much,

**Comment by elahia** [comment]
Hi James,
I changed the scenario of my prj someway that there is no need to calling weka! but still i have some question about docerizing my prj! So please let me make an overview of my prj for you  at first, then i will ask you my questions!

1. openface will provide me with face data by a csv file and as it is running on visualstudio2015, then i need to create an image which is able to run vs2015, Am i correct?

2. I wrote a program for analyzing the voice of the user in Matlab, so i need another container which is able to run Matlab and my code,

3. the result of openface and Matlab code has to be sent to a python program for the final decision, so i need another container which runs python!


so totally i need 3 containers with a shared volume to share the variables and data and a dockercompose file to use these three images! 
Atually, i know what should i do but i don't know HOW to start!! so can you please help me to find my way!
in addition, i'm on ubuntu 14.04,  

Best Regards
Elahe

**Comment by jamesmstone** [comment]
Hi Elahe,

1st if you haven't already, you'll need to have `docker` and
`docker-compose` installed. I find the easiest way to do that is by using
this [script](
https://gist.github.com/wdullaer/f1af16bd7e970389bad3#GISTCOMMENT-1589374)
, although I have never tried this on 14.04.

2nd you will need to create a `docker-compose.yml`
As a start point yours might look something like this:

```
version: '3'
services:
  matlab:
    volumes:
      - data-volume:/data
    build:
      context: ./matlab
      dockerfile: Dockerfile-matlab
  python:
    image: python
    volumes:
      - data-volume:/data
  openface:
    image: openface
    volumes:
      - data-volume:/data

volumes:
  data-volume:

```

Which you could run by `docker-compose up
`
what language are you using in vs2015, you will need to use / write a
docker image so you can run it directly without vs2015.

Thanks
James

**Comment by elahia** [comment]
Dear James,
Thank you for your comment,
Yes i already installed Docker and docker-compose,  about the used language in vs2015 the openface is written in c++, 
for running matlab in docker i realized that i need a runtime version of my matlab code, which make all its functions and dependencies available, 
so i think for openface also i need to make it as an app and then try to run that app in docker! Did you hear anything about it? because openface is a big and complex package with lots of dependencies subfolders and etc, how docker can manage all these things!

Regards,
Elahe,

**Comment by jamesmstone** [comment]
closing. Fingers crossed you solved this!
